apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-router
  labels:
    app: selenium-router
    name: selenium-router
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-router
  template:
    metadata:
      labels:
        app: selenium-router
        name: selenium-router
        component: "selenium-grid-4"
    spec:
     containers:
       - name: selenium-router
         image: selenium/router:4.9.1-20230508
         env:
           - name: SE_OPTS
             value: "--log-level FINE"
           - name: SE_JAVA_OPTS
             value: "-Xmx1024m"
           - name: SE_DISTRIBUTOR_HOST
             value: "selenium-distributor"
           - name: SE_DISTRIBUTOR_PORT
             value: "5553"
           - name: SE_SESSIONS_MAP_HOST
             value: "selenium-sessions"
           - name: SE_SESSIONS_MAP_PORT
             value: "5556"
           - name: SE_NODE_HOST
             value: "selenium-chrome-node"
           - name: SE_NODE_PORT
             value: "5555"
         ports:
           - containerPort: 4444
             protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: selenium-router
  labels:
    name: selenium-router
    component: "selenium-grid-4"
spec:
  type: ClusterIP
  selector:
    app: selenium-router
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444